require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

inherit_from:
  - .rubocop_base.yml
  - .rubocop_rspec.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 7.0.4
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/environments/*
    - config/puma.rb
    - db/migrate/*
    - db/*
    - vendor/**/*
    - tmp/**/*
    - node_modules/**/*
