Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 198
