default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trainerintouch_development

test:
  <<: *default
  database: trainerintouch_test

production:
  <<: *default
  database: trainerintouch_production
  username: trainerintouch
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
